server.forward-headers-strategy=native
server.servlet.session.cookie.http-only=true
server.servlet.session.timeout=2h
server.compression.enabled=true
server.shutdown=graceful
spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB